// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrF2XBb45l-gb-N44nr8uHAYEHyJGH3iw',
    appId: '1:871908348230:android:9e25e805141a3bbd525547',
    messagingSenderId: '871908348230',
    projectId: 'sake-83f09',
    storageBucket: 'sake-83f09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4u5KbdioBik-jk9tfC23tYqHya51vt0w',
    appId: '1:871908348230:ios:4fc549e4297cf96e525547',
    messagingSenderId: '871908348230',
    projectId: 'sake-83f09',
    storageBucket: 'sake-83f09.appspot.com',
    iosBundleId: 'com.example.sake',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4u5KbdioBik-jk9tfC23tYqHya51vt0w',
    appId: '1:871908348230:ios:5722a42d01cff94f525547',
    messagingSenderId: '871908348230',
    projectId: 'sake-83f09',
    storageBucket: 'sake-83f09.appspot.com',
    iosBundleId: 'com.example.sake.RunnerTests',
  );
}
